### PR TITLE
kitakami: sepolicy: Fix partitions paths

### PR DESCRIPTION
**Pull request by humberos**
Signed-off-by: Humberto Borba humberos@gmail.com

### CODE REVIEW

**Comment by jerpelea** [comment]
Tbis will create conflict with paths hardlinked in blobs

**Comment by humberos** [comment]
Anyway, the created link on init.rc isn't /dev/block/bootdevice/by-name/ ?

**Comment by jerpelea** [comment]
Yes and that one is critical

**Comment by humberos** [comment]
So, this patch needs some changes because the current path is:
/dev/block/platform/soc.0
      !=
/dev/block/bootdevice

Please, reopen PR then I will rebase it.

**Comment by jerpelea** [comment]
Can not be reopened please create a new one

**Pull request closed without merging**
