### PR TITLE
Remove device/sony/kitakami/overlay/frameworks

### PR DESCRIPTION
**Pull request by Professor-Berni**
This path is not longer needed due to this commit: https://github.com/sonyxperiadev/device-sony-common/commit/9c889b0342eecd7b6692fc2e83cac8e5f06e08da#commitcomment-26717968

### CODE REVIEW

**Comment by jerpelea** [comment]
unfortunately you pushed many commits

**Comment by jerpelea** [comment]
git revert 4562570f549214655d83610359abb4d45985d8d5

**Comment by Professor-Berni** [comment]
I've done so. I hope, it's better now... Sorry for my mistake!!

**Comment by jerpelea** [comment]
no problem
just
git pull
git revert
git push

and open a new PR

**Comment by Professor-Berni** [comment]
I'm so sorry, but I'm not able to do this. I've never uploaded a change, so this is absolutely new for me!
Is there a tutorial available?

**Comment by jerpelea** [comment]
no worry i will try tommake a howto contribute howto
i fixed it for now

thanks

**Pull request closed without merging**
