### PR TITLE
kitakami: Allow everyone to read /firmware

### PR DESCRIPTION
**Pull request by oshmoun**
This should fix the fact that the keymaster firmware isn't
being loaded.

### CODE REVIEW

**Comment by BuzzBumbleBee** [comment]
Fixes keymaster on ivy, endless "unable to open" errors without

**Comment by BuzzBumbleBee** [comment]
After some testing we can mount this without execute permissions, like

```
/dev/block/bootdevice/by-name/modem        /firmware    vfat    ro,shortname=lower,uid=1000,gid=1000,dmask=222,fmask=222,context=u:object_r:firmware_file:s0 wait
```

**Comment by jerpelea** [comment]
Please update commit!

**Comment by oshmoun** [comment]
commit updated to remove execute permissions

**Pull request merged**
