### PR TITLE
kitakami: Fix liblights for Xperia Z4 Tablets

### PR DESCRIPTION
**Pull request by humberos**
Signed-off-by: Humberto Borba humberos@gmail.com

### CODE REVIEW

**Comment by jerpelea** [comment]
Why don't you rename backlight in kernel instead of patching userspace?

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/kernel/blob/platform/arch/arm/boot/dts/qcom/msm8994-kitakami_karin_common.dtsi

**Comment by humberos** [comment]
anyway the userspace requires changes due to max_brightness (4095).

**Comment by jerpelea** [comment]
Also Fix kernel to 255

**Pull request closed without merging**
