### PR TITLE
kitakami: remove SONY_ROOT define

### PR DESCRIPTION
**Pull request by andi34**
Google doesn't use this simplified way

Change-Id: Ib0bb63bd9b80c145ccb1ac88bbf5af25c52dab9c

### CODE REVIEW

**Comment by andi34** [comment]
Seems like google doesn't seem to follow one way:
https://android.googlesource.com/device/moto/shamu/+/android-6.0.0_r1/device.mk#51

https://android.googlesource.com/device/htc/flounder/+/android-6.0.0_r1/device.mk#48

**Comment by alviteri** [comment]
This change has sense?

**Comment by andi34** [comment]
If it is the goal to follow AOSP way, yes.

About https://github.com/andi34/device-sony-kitakami/commit/0aa2908dc256e1b388c2590601ac51c48fc2fb2b i was told to follow nexus devices

**Comment by andi34** [comment]
See https://github.com/sonyxperiadev/device-sony-kitakami/pull/62 for reference.

**Comment by jerpelea** [comment]
lets try and keep it short. paths are too long and repetitive !

**Pull request closed without merging**
