### PR TITLE
kitakami: fstab: Update fstab on Android M

### PR DESCRIPTION
**Pull request by humberos**
Reference:
https://android.googlesource.com/device/moto/shamu/+/master/fstab.shamu

Signed-off-by: Humberto Borba humberos@gmail.com

### CODE REVIEW

**Comment by jerpelea** [comment]
Please fix white spaces

**Comment by humberos** [comment]
Did you mean to use tab instead of spaces?

https://gist.github.com/humberos/2a0b154fd8f2a1badad0
This is the file after this patch.

**Comment by humberos** [comment]
updated.
please, just let me know if it still not good.

**Comment by jerpelea** [comment]
https://github.com/humberos/device-sony-kitakami/commit/25cf9aaafd11ad46cdf7177e02d313d343c631f0
Shows a lot of diffs because of whitespaces

**Comment by humberos** [comment]
yes, I am using at least 4 spaces between columns.
Also, I fixed columns alignment.
Please check the result here:
https://github.com/humberos/device-sony-kitakami/blob/fstab/rootdir/fstab.kitakami

**Comment by jerpelea** [comment]
I cant see the diff in your link.please update pr

**Comment by humberos** [comment]
ok, I will revert it to original patch.
Since this file is using spaces instead of tabs then we'll get spaces diffs between patches.

**Comment by humberos** [comment]
Ready to go!

**Pull request closed without merging**
