### PR TITLE
Kitakami: add missing symlink for NFC

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri davidteri91@gmail.com

### CODE REVIEW

**Comment by alviteri** [comment]
@humberos ping!

**Comment by humberos** [comment]
@alviteri what device ?
I have no NFC issues on Karin!

**Comment by alviteri** [comment]
yeah Humberto I can confirm it ... on AOSP is OK ... this commit is for CM .... it is still using old way for NFC ......

**Comment by jerpelea** [comment]
this is not cm!

**Pull request closed without merging**
