### PR TITLE
Power hal

### PR DESCRIPTION
**Pull request by humberos**
It requires new blobs.
So, I am uploading it just as a reference for now.

### CODE REVIEW

**Comment by jerpelea** [comment]
this one requires proper testing

**Comment by humberos** [comment]
I did it by using 5.1.1 blobs but they are not working.
We need to update blobs with the correct IDs.

I/QCOMPowerHAL (968): QCOM power HAL initing
E/QCOMPowerHAL (968): Invalid hint ID.
E/QCOMPowerHAL (968): Failed to acquire lock.

**Comment by alviteri** [comment]
why not add for all platforms?

https://www.codeaurora.org/cgit/external/gigabyte/device/qcom/common/tree/power?h=caf%2FLA.HB.1.1.1_rb1.12

is just an idea

**Comment by humberos** [comment]
I've just followed aosp. ;)
Em 16/11/2015 12:20 PM, "David Viteri" notifications@github.com escreveu:

**Comment by humberos** [comment]
It can be closed, right?

**Pull request closed without merging**
