### PR TITLE
Charger mode changes

### PR DESCRIPTION
**Pull request by humberos**
1. Organize the charger mode sequence

### CODE REVIEW

**Comment by jerpelea** [comment]
Please leave services in the init.kitakami.rc

**Comment by alviteri** [comment]
wait I am little lost ... rmt_storage isn't related modem stuff ???

**Comment by humberos** [comment]
Done.
It's ready to go.

**Comment by jerpelea** [comment]
Please drop first patch
It contains services

**Comment by humberos** [comment]
Done.

**Pull request merged**
